#Social Login
social_login:
    facebook:
        enabled: false
        id:
        secret:
        scope: email
    twitter:
        enabled: false
        key:
        secret:
        scope:
    google:
        enabled: false
        id:
        secret:
        scope: 'https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email'
    yahoo:
        enabled: false
        key:
        secret:
        scope:
    github:
        enabled: false
        id:
        secret:
        scope:
