# Login
login:
    pattern: /login
    controller: User
    action:
        get: LoginGetController
        post: LoginSaveController
    extra:
        layout: login
    extra:
        warder:
            require_login: false

# Logout
logout:
    pattern: /logout
    controller: User
    action:
        '*': LogoutSaveController
    extra:
        warder:
            require_login: false

# Profile
profile:
    pattern: /profile/(id)
    controller: User\Profile
    action:
        get: GetController
    extra:
        layout: profile

profile_edit:
    pattern: /profile
    controller: User\Profile
    extra:
        layout: edit
        warder:
            require_login: true

# Registration
registration:
    pattern: /registration
    controller: User\Registration
    action:
        get: RegistrationGetController
        post: RegistrationSaveController
    extra:
        layout: registration
        warder:
            require_login: false

registration_activate:
    pattern: /registration/activate
    controller: User\Registration
    action:
        '*': ActivateSaveController
    extra:
        warder:
            require_login: false

#Social
social_login:
    pattern: /social-login/(provider)
    controller: User
    action:
        '*': LoginSaveController
    extra:
        warder:
            require_login: false

social_auth:
    pattern: /social-auth
    controller: User
    action:
        '*': AuthController
    extra:
        warder:
            require_login: false

# Forget
forget_request:
    pattern: /forget/request
    controller: User\Forget
    action:
        get: RequestGetController
        post: RequestSaveController
    extra:
        layout: forget.request
        warder:
            require_login: false

forget_confirm:
    pattern: /forget/confirm
    controller: User\Forget
    action:
        get: ConfirmGetController
        post: ConfirmSaveController
    extra:
        layout: forget.confirm
        warder:
            require_login: false

forget_reset:
    pattern: /forget/reset
    controller: User\Forget
    action:
        get: ResetGetController
        post: ResetSaveController
    extra:
        layout: forget.reset
        warder:
            require_login: false

forget_complete:
    pattern: /forget/complete
    controller: User\Forget
    action:
        get: CompleteGetController
        post: ComleteSaveController
    extra:
        layout: forget.complete
        warder:
            request_login: false
